name: nlp
channels:
  - pytorch
  - defaults
  - pyg
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - notebook
  - ipykernel
  - ipywidgets
  - git-lfs
  - libsndfile
  - numpy=1.23.5
  - pip:
      - -r requirements.txt